version: 1.0.{build}

image: Visual Studio 2017

shallow_clone: true
clone_depth: 1

configuration: Release

environment:
  matrix:
  - platform: Win32
    PYTHONPATH: C:\Python37

  - platform: x64
    PYTHONPATH: C:\Python37-x64

build:
  project: pygin/pygin.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: >-
    cd pygin

    pack.cmd
artifacts:
- path: '**\*.7z'
